spring.datasource.url=jdbc:mysql://localhost:3306/apitool
spring.datasource.username=root
spring.datasource.password=2420030556

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8089